import { importPackageModule } from '../packageLoader.js';

const implementation = await importPackageModule('imageEditorCore/document.js');

export const {
    IMAGE_DOCUMENT_VERSION,
    MAX_HISTORY_ENTRIES,
    MIN_NORMALIZED_SIZE,
    HAND_DRAWN_STYLE,
    HAND_DRAWN_ROUGHNESS,
    HANDWRITTEN_FONT_FAMILY,
    ANNOTATION_TYPES,
    RESIZE_HANDLES,
    DEFAULT_ANNOTATION_STYLE,
    clamp,
    createAnnotationId,
    normalizePoint,
    getArrowBendPoint,
    getArrowControlPoint,
    getArrowPoint,
    normalizeRect,
    clampRect,
    rectsIntersect,
    normalizeCropRect,
    normalizeAnnotation,
    createAnnotation,
    getAnnotationBounds,
    annotationIntersectsRect,
    hitTestAnnotation,
    hitTestAnnotations,
    getResizeHandles,
    hitTestResizeHandle,
    mapAnnotationGeometry,
    moveAnnotationGeometry,
    resizeBounds,
    resizeAnnotationGeometry,
    transformTextOrientation,
    remapAnnotationForCrop,
    rotateAnnotation,
    flipAnnotation,
    normalizeImageTransform,
    ImageDocument,
} = implementation;
