import { importPackageModule } from '../packageLoader.js';

const implementation = await importPackageModule('providerRuntime/remoteProvider.js');

export const {
    isTransientTlsError,
    isNetworkError,
    streamChunks,
    ServerSentEventDecoder,
    extractOpenAiServerToolResults,
    extractAnthropicServerToolResults,
    extractGeminiServerToolResults,
    extractChatCompletionServerToolResults,
    extractOpenAiToolCalls,
    extractChatCompletionToolCalls,
    extractAnthropicToolCalls,
    extractGeminiToolCalls,
    openAiMessages,
    openAiCompatibleMessages,
    anthropicPayloadMessages,
    geminiPayload,
    buildOpenAiResponsesBody,
    buildOpenAiCompatibleChatBody,
    buildAnthropicMessagesBody,
    buildGeminiGenerateContentBody,
    extractOpenAiText,
    extractOpenAiReasoning,
    extractOpenAiUsage,
    extractOpenAiFinishReason,
    extractOpenAiResponse,
    extractChatCompletionText,
    extractChatCompletionReasoning,
    extractChatCompletionUsage,
    extractChatCompletionFinishReason,
    extractChatCompletionResponse,
    extractAnthropicText,
    extractAnthropicReasoning,
    extractAnthropicUsage,
    extractAnthropicFinishReason,
    extractAnthropicResponse,
    extractGeminiText,
    extractGeminiReasoning,
    extractGeminiUsage,
    extractGeminiFinishReason,
    extractGeminiProviderParts,
    extractGeminiResponse,
    extractDiscoveredModels,
    discoverOpenAiCompatibleModels,
    discoverAnthropicModels,
    discoverGeminiModels,
    OpenAiResponsesProvider,
    OpenAiCompatibleChatProvider,
    AnthropicMessagesProvider,
    GeminiGenerateContentProvider,
} = implementation;
